# Docker Compose for Coolify compatibility
# Coolify will manage external services (database, redis)
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-80}:80"
    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - BROADCAST_DRIVER=${BROADCAST_DRIVER:-log}
      - CACHE_DRIVER=${CACHE_DRIVER:-file}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION:-sync}
      - SESSION_DRIVER=${SESSION_DRIVER:-file}
    volumes:
      - storage_data:/var/www/html/storage/app
      - storage_logs:/var/www/html/storage/logs
    restart: unless-stopped

volumes:
  storage_data:
  storage_logs: