# Production override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.8'

services:
  app:
    restart: always
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=warning
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nginx:
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    # Remove port 80 if using Cloudflare Tunnel
    ports:
      - "443:443"

  db:
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-strong_root_password_here}
      MYSQL_PASSWORD: ${DB_PASSWORD:-strong_password_here}
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    volumes:
      - dbdata:/var/lib/mysql
      # Add custom MySQL configuration
      - ./docker/mysql/prod.cnf:/etc/mysql/conf.d/prod.cnf

  redis:
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_password_here}
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  queue:
    restart: always
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  websockets:
    restart: always
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Remove node service in production (assets should be pre-built)
  node:
    profiles:
      - development

  # Add monitoring (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - laravel